server:
  port: ${APP_PORT}

spring:
  application:
    name: account
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      initialization-fail-timeout: 30000
  jpa:
    hibernate:
      ddl-auto: none
    defer-datasource-initialization: true
    open-in-view: false
    show-sql: false
  rabbitmq:
    host: ${RBQ_HOST}
    port: ${RBQ_PORT}
    username: ${RBQ_USER}
    password: ${RBQ_PASSWORD}
  sql:
    init:
      mode: always
      separator: "@@"

springdoc:
  swagger-ui:
    path: /swagger-ui.html

rabbitmq:
  clients:
    exchange: clients.exchange
    verify-routing-key: clients.verify-request
